### ISSUE TITLE
collapsed thread icon not showing

### ISSUE THREAD

**Issue by JohnRDOrazio** [EstudioNexos/mabola#22]
https://github.com/EstudioNexos/mabola/blob/478a678a4c890008e96bdee313086d38d2f46f18/styles.css#L772

This line is incorrect and the collapsed thread icon is not showing. The correct icon is at position "0px -1136px". I'm not sure why but simply adding a 0 in front of the -100px actually seems to fix it :
```css
background: rgba(0, 0, 0, 0) url("images/listicons.png") no-repeat scroll 0 -100px 0;
```

**Comment by JohnRDOrazio** [comment]
I see why adding a 0 in front fixes the problem: because since it's incorrect syntax the rule is being canceled and the rule from larry theme is being automatically enforced
![css mabola](https://user-images.githubusercontent.com/231298/53211442-724e0280-3641-11e9-9b8e-45e211a1bc7b.jpg)

**Comment by JohnRDOrazio** [comment]
So I'm guessing the rule was supposed to hide a bunch of icons which would be otherwise shown in larry theme? But collapsed / expanded icons are visually important. I can't even see that there is a thread available if I don't have a collapsed icon in view. So I separated the rules out like this:
```css
.messagelist tr > .threads .listmenu, .messagelist tr > .attachment span.attachment, .messagelist tr > .attachment span.report, .messagelist tr > .priority span.priority, .messagelist tr > .priority span.prio1, .messagelist tr > .priority span.prio2, .messagelist tr > .priority span.prio3, .messagelist tr > .priority span.prio4, .messagelist tr > .priority span.prio5, .messagelist tr > .flag span.flagged, .messagelist tr > .flag span.unflagged, .messagelist tr > .flag span.unflagged:hover, .messagelist tr > .status span.status, .messagelist tr > .status span.msgicon, .messagelist tr > .status span.deleted, .messagelist tr > .status span.unread, .messagelist tr > .status span.unreadchildren, .messagelist tr > .subject span.msgicon, .messagelist tr > .subject span.deleted, .messagelist tr > .subject span.unread, .messagelist tr > .subject span.replied, .messagelist tr > .subject span.forwarded, .messagelist tr > .subject span.unreadchildren {
    background: rgba(0, 0, 0, 0) url("images/listicons.png") no-repeat scroll -100px 0;
}

.messagelist tr td div.collapsed {
    background: rgba(0, 0, 0, 0) url("images/listicons.png") no-repeat scroll 0 -1137px;
}

.messagelist tr td div.expanded {
    background: rgba(0, 0, 0, 0) url("images/listicons.png") no-repeat scroll 0 -1157px;
}
```
